CREATE TABLE [dbo].[Shipping_list_History] (
    [History_ID]               BIGINT       IDENTITY (1, 1) NOT NULL,
    [Shipping_list_ID]         INT          NOT NULL,
    [Site]                     VARCHAR (2)  NOT NULL,
    [Project]                  VARCHAR (15) NULL,
    [Ship_Type]                VARCHAR (15) NULL,
    [PN]                       VARCHAR (50) NOT NULL,
    [Ship_date]                DATE         NULL,
    [Customer_Code]            VARCHAR (15) NOT NULL,
    [PO]                       VARCHAR (25) NULL,
    [PO_End]                   VARCHAR (25) NULL,
    [Carton_ID_Inner]          VARCHAR (15) NULL,
    [Carton_ID_Outter]         VARCHAR (15) NULL,
    [Lot_Wafer_Box_ID]         VARCHAR (15) NOT NULL,
    [Lotid_Wafer]              VARCHAR (15) NULL,
    [Ship_Qty]                 INT          NULL,
    [TrayLastSN]               VARCHAR (20) NULL,
    [Package_Type]             VARCHAR (15) NULL,
    [Lot_ID]                   VARCHAR (15) NULL,
    [Wafer_ID]                 VARCHAR (15) NULL,
    [Box_ID]                   VARCHAR (15) NULL,
    [TrackingNumber]           VARCHAR (50) NULL,
    [OEM_Ship_date]            DATE         NULL,
    [Cdt]                      DATETIME     NULL,
    [Udt]                      DATETIME     NULL,
    [GenerateShippingData_Cdt] DATETIME     NULL,
    [ImportTraySN_Cdt]         DATETIME     NULL,
    [UpdateUser]               [sysname]    CONSTRAINT [DF_Shipping_list_UpdateUser] DEFAULT (original_login()) NOT NULL,
    [UpdateDate]               DATETIME     CONSTRAINT [DF_Shipping_list_UpdateDate] DEFAULT (getdate()) NOT NULL,
    [UpdateHost]               VARCHAR (64) CONSTRAINT [DF_Shipping_list_UpdateHost] DEFAULT (host_name()) NOT NULL,
    CONSTRAINT [PK_Shipping_list_History] PRIMARY KEY CLUSTERED ([History_ID] ASC)
);

