

/*
-- =============================================
-- Author:		Jackie Chen
-- Create date: 2025/11/30
-- Description:	Refer Z_Wafer, Update Wafer
-- Notes:

Change Log:
-- =============================================
*/
CREATE PROCEDURE [dbo].[uspUpdate_Wafer_Batch]
AS
BEGIN
    SET NOCOUNT ON;

	UPDATE T SET T.[Wafer号] = S.[Wafer号]
		, T.[特殊备注] = S.[特殊备注]
		, T.[测试数量] = S.[测试数量]
		, T.[测试通过数量bin1] = S.[测试通过数量bin1]
		, T.[测试不良数量bin2] = S.[测试不良数量bin2]
		, T.[划片不良数量bin23] = S.[划片不良数量bin23]
		, T.[划片后sampling bin24] = S.[划片后sampling bin24]
		, T.[分拣不良数量bin25] = S.[分拣不良数量bin25]
		, T.[挑粒投入] = S.[挑粒投入]
		, T.[挑粒产出] = S.[挑粒产出]
		, T.[目检产出] = S.[目检产出]
		, T.[划片开始时间] = S.[划片开始时间]
		, T.[划片结束时间] = S.[划片结束时间]
		, T.[挑粒开始时间] = S.[挑粒开始时间]
		, T.[挑粒结束时间] = S.[挑粒结束时间]
		, T.[复判照片结束时间] = S.[复判照片结束时间]
		, T.[OQC结束时间] = S.[OQC结束时间]
		, T.[包装结束时间] = S.[包装结束时间]
		, T.[测试良率] = S.[测试良率]
		, T.[挑粒良率] = S.[挑粒良率]
		, T.[目检良率] = S.[目检良率]
		, T.[滚动良率] = S.[滚动良率]
		, T.[目检结束时间] = S.[目检结束时间]
		, T.[划痕HH] = S.[划痕HH]
		, T.[扎痕ZH] = S.[扎痕ZH]
		, T.[脏污ZW] = S.[脏污ZW]
		, T.[崩裂BL] = S.[崩裂BL]
		, T.[测试开始时间] = S.[测试开始时间]
		, T.[测试结束时间] = S.[测试结束时间]
		, T.[AOI开始] = S.[AOI开始]
		, T.[AOI结束] = S.[AOI结束]
		, T.[目检开始时间] = S.[目检开始时间]
		, T.[复判照片开始时间] = S.[复判照片开始时间]
		, T.[OQC开始时间] = S.[OQC开始时间]
		, T.[包装开始时间] = S.[包装开始时间]
		, T.[pn] = S.[pn]
		, T.[Lot号] = S.[Lot号]
		, T.[Lead TIME] = S.[Lead TIME]
		, T.[复判-挑粒结束] = S.[复判-挑粒结束]
		, T.[目检标准] = S.[目检标准]
		, T.[流程] = S.[流程]
		, T.[SourceName] = S.[SourceName]
		, T.[FileModifiedTime] = S.[FileModifiedTime]
		, T.[更新日期] = S.[更新日期]
		, T.Udt = GETDATE()
	FROM dbo.Z_Wafer AS S
	JOIN dbo.Wafer AS T ON S.[Wafer号] = T.[Wafer号]

	INSERT dbo.Wafer([Wafer号]
		, [特殊备注]
		, [测试数量]
		, [测试通过数量bin1]
		, [测试不良数量bin2]
		, [划片不良数量bin23]
		, [划片后sampling bin24]
		, [分拣不良数量bin25]
		, [挑粒投入]
		, [挑粒产出]
		, [目检产出]
		, [划片开始时间]
		, [划片结束时间]
		, [挑粒开始时间]
		, [挑粒结束时间]
		, [复判照片结束时间]
		, [OQC结束时间]
		, [包装结束时间]
		, [测试良率]
		, [挑粒良率]
		, [目检良率]
		, [滚动良率]
		, [目检结束时间]
		, [划痕HH]
		, [扎痕ZH]
		, [脏污ZW]
		, [崩裂BL]
		, [测试开始时间]
		, [测试结束时间]
		, [AOI开始]
		, [AOI结束]
		, [目检开始时间]
		, [复判照片开始时间]
		, [OQC开始时间]
		, [包装开始时间]
		, [pn]
		, [Lot号]
		, [Lead TIME]
		, [复判-挑粒结束]
		, [目检标准]
		, [流程]
		, [SourceName]
		, [FileModifiedTime]
		, [更新日期])
		SELECT S.[Wafer号]
		, S.[特殊备注]
		, S.[测试数量]
		, S.[测试通过数量bin1]
		, S.[测试不良数量bin2]
		, S.[划片不良数量bin23]
		, S.[划片后sampling bin24]
		, S.[分拣不良数量bin25]
		, S.[挑粒投入]
		, S.[挑粒产出]
		, S.[目检产出]
		, S.[划片开始时间]
		, S.[划片结束时间]
		, S.[挑粒开始时间]
		, S.[挑粒结束时间]
		, S.[复判照片结束时间]
		, S.[OQC结束时间]
		, S.[包装结束时间]
		, S.[测试良率]
		, S.[挑粒良率]
		, S.[目检良率]
		, S.[滚动良率]
		, S.[目检结束时间]
		, S.[划痕HH]
		, S.[扎痕ZH]
		, S.[脏污ZW]
		, S.[崩裂BL]
		, S.[测试开始时间]
		, S.[测试结束时间]
		, S.[AOI开始]
		, S.[AOI结束]
		, S.[目检开始时间]
		, S.[复判照片开始时间]
		, S.[OQC开始时间]
		, S.[包装开始时间]
		, S.[pn]
		, S.[Lot号]
		, S.[Lead TIME]
		, S.[复判-挑粒结束]
		, S.[目检标准]
		, S.[流程]
		, S.[SourceName]
		, S.[FileModifiedTime]
		, S.[更新日期]
		FROM dbo.Z_Wafer AS S
		LEFT JOIN dbo.Wafer AS T ON S.[Wafer号] = T.[Wafer号]
		WHERE T.[Wafer号] IS NULL

END;
GO
GRANT EXECUTE
    ON OBJECT::[dbo].[uspUpdate_Wafer_Batch] TO [Production]
    AS [dbo];

